/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/field-manual.ts
 * Command: astryx theme build src/themes/field-manual.ts
 * Generated: 2026-07-23T11:17:11.823Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const fieldManualTheme: DefinedTheme;
