import { Metadata } from "next";
import { PapHeader } from "@/components/header";
import { Section } from "@astryxdesign/core/Section";
import { VStack, HStack } from "@astryxdesign/core/Stack";
import { Text, Heading } from "@astryxdesign/core/Text";
import { Link } from "@astryxdesign/core/Link";

function BulletList({ items }: { items: string[] }) {
  return (
    <VStack gap={1.5}>
      {items.map((item) => (
        <HStack key={item} gap={2}>
          <Text type="body" color="secondary">•</Text>
          <Text type="body" color="secondary">{item}</Text>
        </HStack>
      ))}
    </VStack>
  );
}

export const metadata: Metadata = {
  title: "Terms of Use — Interview Lab",
  description: "Terms for using Interview Lab, a free companion to Project Amazon PH Academy.",
};

export default function TermsPage() {
  return (
    <>
      <PapHeader />
      <Section variant="transparent" paddingBlock={10}>
        <VStack gap={6} maxWidth={640} className="mx-auto">
          <VStack gap={2}>
            <Heading level={1} type="display-2">Terms of Use</Heading>
            <Text type="supporting" size="sm">
              Questions about these terms? Contact{" "}
              <Link href="mailto:support@interview-lab.vercel.app">support@interview-lab.vercel.app</Link>.
            </Text>
          </VStack>

          <VStack gap={2}>
            <Heading level={2} type="display-3">The service</Heading>
            <Text type="body" color="secondary">
              Interview Lab is a free companion to Project Amazon PH Academy. All features are
              available to every account at no cost — there are no paid tiers.
            </Text>
          </VStack>

          <VStack gap={2}>
            <Heading level={2} type="display-3">AI-generated content</Heading>
            <BulletList items={[
              "Mock interview feedback, resume reviews, cover letters, and scores are generated by an AI model and may be inaccurate or incomplete. Use your own judgment before relying on them.",
              "We do not guarantee job placement, interview outcomes, or income as a result of using this platform.",
              "You are responsible for the accuracy of any experience, tools, or credentials you claim in resumes, cover letters, or interview answers generated with our help — do not use the platform to fabricate work history or qualifications.",
            ]} />
          </VStack>

          <VStack gap={2}>
            <Heading level={2} type="display-3">Acceptable use</Heading>
            <Text type="body" color="secondary">
              Don&apos;t use the platform to submit unlawful, abusive, or fraudulent content, or to
              attempt to disrupt or gain unauthorized access to the service.
            </Text>
          </VStack>

          <VStack gap={2}>
            <Heading level={2} type="display-3">Changes</Heading>
            <Text type="body" color="secondary">
              We may update these terms or the product as it evolves. Continued use of the platform
              after a change means you accept the updated terms.
            </Text>
          </VStack>

          <Link href="/">← Back to Home</Link>
        </VStack>
      </Section>
    </>
  );
}
