import { Metadata } from "next";
import { PapHeader } from "@/components/header";

export const metadata: Metadata = {
  title: "Terms of Use — Interview Lab",
  description: "Terms for using Interview Lab, a free companion to Project Amazon PH Academy.",
};

export default function TermsPage() {
  return (
    <>
    <PapHeader />
    <div className="min-h-[100dvh] bg-background px-6 py-16">
      <div className="max-w-2xl mx-auto prose prose-neutral">
        <h1 className="text-3xl font-heading font-bold text-ink-900 mb-2">Terms of Use</h1>
        <p className="text-ink-500 text-sm mb-8">
          Questions about these terms? Contact{" "}
          <a href="mailto:support@interview-lab.vercel.app" className="text-accent hover:underline">
            support@interview-lab.vercel.app
          </a>.
        </p>

        <h2 className="font-heading font-semibold text-ink-900 mt-8 mb-2">The service</h2>
        <p className="text-ink-700">
          Interview Lab is a free companion to Project Amazon PH Academy. All features are
          available to every account at no cost — there are no paid tiers.
        </p>

        <h2 className="font-heading font-semibold text-ink-900 mt-8 mb-2">AI-generated content</h2>
        <ul className="list-disc pl-5 space-y-1 text-ink-700">
          <li>
            Mock interview feedback, resume reviews, cover letters, and scores are generated by
            an AI model and may be inaccurate or incomplete. Use your own judgment before relying
            on them.
          </li>
          <li>
            We do not guarantee job placement, interview outcomes, or income as a result of using
            this platform.
          </li>
          <li>
            You are responsible for the accuracy of any experience, tools, or credentials you
            claim in resumes, cover letters, or interview answers generated with our help — do
            not use the platform to fabricate work history or qualifications.
          </li>
        </ul>

        <h2 className="font-heading font-semibold text-ink-900 mt-8 mb-2">Acceptable use</h2>
        <p className="text-ink-700">
          Don&apos;t use the platform to submit unlawful, abusive, or fraudulent content, or to
          attempt to disrupt or gain unauthorized access to the service.
        </p>

        <h2 className="font-heading font-semibold text-ink-900 mt-8 mb-2">Changes</h2>
        <p className="text-ink-700">
          We may update these terms or the product as it evolves. Continued use of the platform
          after a change means you accept the updated terms.
        </p>

        <a href="/" className="inline-block mt-10 text-accent hover:underline">
          ← Back to Home
        </a>
      </div>
    </div>
    </>
  );
}
