import { db } from '@/lib/db';
import { getUserFromRequest } from '@/lib/auth-helpers';
import { NextRequest, NextResponse } from 'next/server';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, TabStopPosition, TabStopType } from 'docx';

// Access tier hierarchy: free < starter < pro
const TIER_HIERARCHY: Record<string, number> = { free: 0, starter: 1, pro: 2 };

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const download = await db.download.findUnique({ where: { id } });

    if (!download) {
      return NextResponse.json({ error: 'Download not found' }, { status: 404 });
    }

    // Validate fileName contains only safe characters
    const safeFileNamePattern = /^[a-zA-Z0-9._-]+$/;
    if (!safeFileNamePattern.test(download.fileName)) {
      return NextResponse.json({ error: 'Invalid file name' }, { status: 400 });
    }

    // Verify the user is authenticated and has sufficient access tier
    const user = await getUserFromRequest(request);
    if (!user) {
      return NextResponse.json({ error: 'Authentication required to download files' }, { status: 401 });
    }

    const userTierLevel = TIER_HIERARCHY[user.subscriptionTier] ?? 0;
    const requiredTierLevel = TIER_HIERARCHY[download.accessTier] ?? 0;
    if (userTierLevel < requiredTierLevel) {
      return NextResponse.json({ error: `This resource requires ${download.accessTier} tier or higher` }, { status: 403 });
    }

    // Increment download count
    await db.download.update({
      where: { id },
      data: { downloadCount: { increment: 1 } },
    });

    // Generate file dynamically based on metadata
    const { title, fileType, category, description, role } = download;

    if (fileType === 'PDF') {
      return await generatePdf(title, description || '', category, role);
    } else if (fileType === 'DOCX') {
      return await generateDocx(title, description || '', category, role);
    } else if (fileType === 'XLSX') {
      return await generateXlsx(title, description || '', category, role);
    }

    // Fallback: generate plain text
    const textContent = buildTextContent(title, description || '', category, role);
    return new NextResponse(textContent, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="${download.fileName.replace(/\.[^.]+$/, '.txt')}"`,
      },
    });
  } catch (error) {
    console.error('Download GET error:', error);
    return NextResponse.json({ error: 'Failed to process download' }, { status: 500 });
  }
}

function buildTextContent(title: string, description: string, category: string, role: string): string {
  const lines: string[] = [];
  lines.push(title);
  lines.push('='.repeat(title.length));
  lines.push('');
  lines.push(`Category: ${category}`);
  lines.push(`Role: ${role}`);
  lines.push('');
  if (description) {
    lines.push(description);
    lines.push('');
  }

  switch (category) {
    case 'Cheat Sheets':
      lines.push('QUICK REFERENCE');
      lines.push('-'.repeat(16));
      lines.push('');
      addCheatSheetContent(lines, role);
      break;
    case 'Checklists':
      lines.push('CHECKLIST');
      lines.push('-'.repeat(10));
      lines.push('');
      addChecklistContent(lines, role);
      break;
    case 'Calculators':
      lines.push('CALCULATOR WORKSHEET');
      lines.push('-'.repeat(21));
      lines.push('');
      addCalculatorContent(lines, role);
      break;
    case 'Resume Templates':
      lines.push('RESUME TEMPLATE');
      lines.push('-'.repeat(16));
      lines.push('');
      addResumeTemplateContent(lines, role);
      break;
    case 'Cover Letters':
      lines.push('COVER LETTER TEMPLATE');
      lines.push('-'.repeat(21));
      lines.push('');
      addCoverLetterContent(lines, role);
      break;
    case 'Plans & Reports':
      lines.push('PLAN / REPORT TEMPLATE');
      lines.push('-'.repeat(22));
      lines.push('');
      addPlanReportContent(lines, role);
      break;
    default:
      lines.push('NOTES');
      lines.push('-'.repeat(5));
      lines.push('');
      lines.push('[Your notes here]');
  }

  lines.push('');
  lines.push('---');
  lines.push('Generated by Amazon VA Interview Lab');
  return lines.join('\n');
}

function addCheatSheetContent(lines: string[], role: string) {
  if (role.includes('PPC')) {
    lines.push('ACoS = Ad Spend / Ad Revenue × 100');
    lines.push('ROAS = Ad Revenue / Ad Spend');
    lines.push('CTR = Clicks / Impressions × 100');
    lines.push('CPC = Total Spend / Total Clicks');
    lines.push('CVR = Orders / Clicks × 100');
    lines.push('');
    lines.push('Campaign Types: Sponsored Products, Sponsored Brands, Sponsored Display');
    lines.push('Match Types: Exact, Phrase, Broad');
    lines.push('Keyword Harvesting: Search term reports → add as exact, negate irrelevant');
  } else if (role.includes('Account')) {
    lines.push('Account Health: Order Defect Rate < 1%, Late Shipment Rate < 4%');
    lines.push('SKU Management: Active, Inactive, Suppressed listings');
    lines.push('FBA Fees: Referral fee + FBA fee + Storage fee');
    lines.push('Reimbursements: Lost/damaged inventory, fee overcharges');
  } else if (role.includes('Listing')) {
    lines.push('Title: Brand + Key Feature + Size/Color + Keyword');
    lines.push('Bullet Points: 5 bullets, feature → benefit format');
    lines.push('Backend Keywords: 250 bytes max, no repeats');
    lines.push('A+ Content: Enhanced brand content for brand-registered sellers');
  } else if (role.includes('Reporting')) {
    lines.push('Key Reports: Search Term, Placement, Campaign, Advertised Product');
    lines.push('Date Ranges: 7-day, 14-day, 30-day for trend analysis');
    lines.push('Pivot Tables: Campaign → Ad Group → Keyword → Search Term');
    lines.push('Key Metrics: Spend, Sales, ACoS, ROAS, Orders, Units');
  } else {
    lines.push('Seller Central Navigation: Catalog → Advertising → Reports → Settings');
    lines.push('Common Acronyms: ASIN, SKU, FBA, FBM, ACoS, ROAS, CTR, CPC');
    lines.push('Key Workflows: Listing creation → Campaign setup → Bid optimization → Reporting');
    lines.push('Client Communication: Weekly updates, monthly strategy reviews');
  }
}

function addChecklistContent(lines: string[], role: string) {
  if (role.includes('PPC')) {
    lines.push('[ ] Review search term reports');
    lines.push('[ ] Add high-converting search terms as exact keywords');
    lines.push('[ ] Negate irrelevant search terms');
    lines.push('[ ] Adjust bids based on ACoS targets');
    lines.push('[ ] Check budget utilization');
    lines.push('[ ] Review placement performance');
    lines.push('[ ] Pause underperforming campaigns/ad groups');
    lines.push('[ ] Update negative keyword lists');
  } else if (role.includes('Account')) {
    lines.push('[ ] Check account health dashboard');
    lines.push('[ ] Review FBA inventory alerts');
    lines.push('[ ] Process reimbursement cases');
    lines.push('[ ] Update listing statuses');
    lines.push('[ ] Review seller feedback');
    lines.push('[ ] Check restock recommendations');
    lines.push('[ ] Monitor stranded inventory');
  } else if (role.includes('Listing')) {
    lines.push('[ ] Review listing quality score');
    lines.push('[ ] Optimize titles with keywords');
    lines.push('[ ] Update bullet points');
    lines.push('[ ] Add A+ content');
    lines.push('[ ] Upload high-quality images');
    lines.push('[ ] Review backend search terms');
    lines.push('[ ] Check for suppressed listings');
  } else if (role.includes('Reporting')) {
    lines.push('[ ] Pull weekly performance reports');
    lines.push('[ ] Update dashboard/spreadsheet');
    lines.push('[ ] Calculate key metrics (ACoS, ROAS, CTR)');
    lines.push('[ ] Identify trends and anomalies');
    lines.push('[ ] Prepare client summary');
    lines.push('[ ] Schedule next review period');
  } else {
    lines.push('[ ] Log in to Seller Central');
    lines.push('[ ] Check notifications and alerts');
    lines.push('[ ] Review advertising performance');
    lines.push('[ ] Check inventory levels');
    lines.push('[ ] Respond to buyer messages');
    lines.push('[ ] Review listing quality');
    lines.push('[ ] Prepare client update');
  }
}

function addCalculatorContent(lines: string[], role: string) {
  if (role.includes('PPC')) {
    lines.push('ACoS Calculator:');
    lines.push('  Ad Spend: [enter amount]');
    lines.push('  Ad Revenue: [enter amount]');
    lines.push('  ACoS = Ad Spend / Ad Revenue × 100 = [result]%');
    lines.push('');
    lines.push('ROAS Calculator:');
    lines.push('  Ad Revenue: [enter amount]');
    lines.push('  Ad Spend: [enter amount]');
    lines.push('  ROAS = Ad Revenue / Ad Spend = [result]x');
    lines.push('');
    lines.push('Break-even ACoS:');
    lines.push('  Product Price: [enter amount]');
    lines.push('  Product Cost: [enter amount]');
    lines.push('  FBA Fees: [enter amount]');
    lines.push('  Referral Fee: [enter amount]');
    lines.push('  Break-even ACoS = (Price - Cost - Fees) / Price × 100 = [result]%');
  } else {
    lines.push('Profit Margin Calculator:');
    lines.push('  Revenue: [enter amount]');
    lines.push('  COGS: [enter amount]');
    lines.push('  FBA Fees: [enter amount]');
    lines.push('  Ad Spend: [enter amount]');
    lines.push('  Profit Margin = (Revenue - COGS - Fees - Ad Spend) / Revenue × 100 = [result]%');
  }
}

function addResumeTemplateContent(lines: string[], role: string) {
  lines.push('[YOUR FULL NAME]');
  lines.push('[City, Country] | [Email] | [Phone] | [LinkedIn/Portfolio URL]');
  lines.push('');
  lines.push('PROFESSIONAL SUMMARY');
  lines.push(`Results-driven ${role || 'Amazon VA'} with [X] years of experience in Amazon marketplace operations. Skilled in [key skills]. Proven track record of [achievements with metrics].`);
  lines.push('');
  lines.push('CORE SKILLS');
  lines.push(`• ${role.includes('PPC') ? 'Amazon PPC Management (Sponsored Products, Brands, Display)' : 'Amazon Seller Central Operations'}`);
  lines.push(`• ${role.includes('PPC') ? 'Keyword Research & Bid Optimization' : 'Listing Optimization & Catalog Management'}`);
  lines.push(`• Data Analysis & Reporting (Excel, Google Sheets)`);
  lines.push(`• Client Communication & Account Management`);
  lines.push('');
  lines.push('PROFESSIONAL EXPERIENCE');
  lines.push('[Job Title] | [Company] | [Date Range]');
  lines.push('• [Action verb + specific task + quantified result]');
  lines.push('• Managed [X] campaigns with $[Y] monthly spend, achieving [Z]% ACoS');
  lines.push('• [Another achievement with metrics]');
  lines.push('');
  lines.push('TOOLS & PLATFORMS');
  lines.push('Amazon Seller Central, Amazon Ads Console, Helium 10, Google Sheets, Excel');
  lines.push('');
  lines.push('EDUCATION');
  lines.push('[Degree] | [University] | [Year]');
}

function addCoverLetterContent(lines: string[], role: string) {
  lines.push('[Date]');
  lines.push('');
  lines.push('[Hiring Manager Name]');
  lines.push('[Company Name]');
  lines.push('');
  lines.push('Dear [Hiring Manager],');
  lines.push('');
  lines.push(`I am writing to express my interest in the ${role || 'Amazon Virtual Assistant'} position at [Company Name]. With my experience in Amazon marketplace operations and commitment to delivering measurable results, I am confident I can make an immediate impact on your team.`);
  lines.push('');
  lines.push(`In my previous role, I [specific achievement with metrics relevant to ${role}]. I am particularly skilled in [2-3 specific skills relevant to the role].`);
  lines.push('');
  lines.push('I would welcome the opportunity to discuss how my skills align with your needs. Thank you for your consideration.');
  lines.push('');
  lines.push('Best regards,');
  lines.push('[Your Name]');
}

function addPlanReportContent(lines: string[], role: string) {
  lines.push('WEEKLY REPORT TEMPLATE');
  lines.push('');
  lines.push('Period: [Start Date] - [End Date]');
  lines.push(`Client: [Client Name]`);
  lines.push(`Role Focus: ${role}`);
  lines.push('');
  lines.push('KEY METRICS');
  lines.push('  Total Spend: $[amount]');
  lines.push('  Total Revenue: $[amount]');
  lines.push('  ACoS: [percentage]%');
  lines.push('  ROAS: [value]x');
  lines.push('  Impressions: [number]');
  lines.push('  Clicks: [number]');
  lines.push('  Orders: [number]');
  lines.push('');
  lines.push('HIGHLIGHTS');
  lines.push('  • [Key achievement or improvement]');
  lines.push('  • [Notable metric change]');
  lines.push('');
  lines.push('ACTION ITEMS');
  lines.push('  • [Planned optimization]');
  lines.push('  • [Budget adjustment needed]');
}

// ---- PDF Generation ----
async function generatePdf(title: string, description: string, category: string, role: string) {
  try {
    // Generate PDF manually to avoid pdfkit font resolution issues in Next.js bundled environment.
    // pdfkit requires AFM font files resolved via __dirname which doesn't work in Next.js.
    const contentLines = getCategoryContent(category, role);
    const pdfContent = buildSimplePdf(title, description, category, role, contentLines);

    const safeName = title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 50);
    return new NextResponse(new Uint8Array(pdfContent), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${safeName}.pdf"`,
      },
    });
  } catch (error) {
    console.error('PDF generation error:', error);
    // Fallback to text
    const textContent = buildTextContent(title, description, category, role);
    return new NextResponse(textContent, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="${title.replace(/[^a-zA-Z0-9]/g, '_')}.txt"`,
      },
    });
  }
}

// Build a minimal valid PDF manually (no external font files needed)
function buildSimplePdf(title: string, description: string, category: string, role: string, contentLines: string[]): Buffer {
  // Collect all lines for the PDF
  const allLines: Array<{ text: string; size: number; bold: boolean; indent: number; color: string }> = [];

  // Title
  allLines.push({ text: title, size: 24, bold: true, indent: 0, color: '0 0 0' });
  allLines.push({ text: `${category}  \u2022  ${role}`, size: 10, bold: false, indent: 0, color: '0.4 0.4 0.4' });
  allLines.push({ text: '', size: 6, bold: false, indent: 0, color: '0 0 0' });

  if (description) {
    allLines.push({ text: description, size: 11, bold: false, indent: 0, color: '0.2 0.2 0.2' });
    allLines.push({ text: '', size: 6, bold: false, indent: 0, color: '0 0 0' });
  }

  for (const line of contentLines) {
    if (line.startsWith('## ')) {
      allLines.push({ text: '', size: 4, bold: false, indent: 0, color: '0 0 0' });
      allLines.push({ text: line.replace('## ', ''), size: 14, bold: true, indent: 0, color: '0 0 0' });
    } else if (line.startsWith('# ')) {
      allLines.push({ text: '', size: 4, bold: false, indent: 0, color: '0 0 0' });
      allLines.push({ text: line.replace('# ', ''), size: 16, bold: true, indent: 0, color: '0 0 0' });
    } else if (line.startsWith('- [ ] ')) {
      allLines.push({ text: `\u2610  ${line.replace('- [ ] ', '')}`, size: 11, bold: false, indent: 20, color: '0 0 0' });
    } else if (line.startsWith('- ')) {
      allLines.push({ text: `\u2022  ${line.replace('- ', '')}`, size: 11, bold: false, indent: 20, color: '0 0 0' });
    } else if (line.trim() === '') {
      allLines.push({ text: '', size: 4, bold: false, indent: 0, color: '0 0 0' });
    } else {
      allLines.push({ text: line, size: 11, bold: false, indent: 0, color: '0 0 0' });
    }
  }

  allLines.push({ text: '', size: 8, bold: false, indent: 0, color: '0 0 0' });
  allLines.push({ text: 'Generated by Amazon VA Interview Lab', size: 8, bold: false, indent: 0, color: '0.6 0.6 0.6' });

  // Build PDF structure
  const objects: string[] = [];
  let objectCount = 0;

  const addObject = (content: string): number => {
    objectCount++;
    objects.push(`${objectCount} 0 obj\n${content}\nendobj`);
    return objectCount;
  };

  // Object 1: Catalog
  const catalogObj = addObject('<< /Type /Catalog /Pages 2 0 R >>');

  // Object 2: Pages (will reference page objects)
  const pagesObj = addObject('<< /Type /Pages /Kids [3 0 R] /Count 1 >>');

  // Build page content stream
  let streamContent = '';
  let y = 770; // Start near top of page

  for (const item of allLines) {
    if (y < 50) break; // Stop if we run off the page

    const fontName = item.bold ? '/F2' : '/F1';
    const x = 50 + item.indent;

    // Escape special PDF characters
    const escapedText = item.text
      .replace(/\\/g, '\\\\')
      .replace(/\(/g, '\\(')
      .replace(/\)/g, '\\)');

    streamContent += `BT\n${fontName} ${item.size} Tf\n${item.color} rg\n${x} ${y} Td\n(${escapedText}) Tj\nET\n`;
    y -= item.size + 4;
  }

  // Object 3: Page
  const streamObjId = addObject(`<< /Length ${streamContent.length} >>\nstream\n${streamContent}\nendstream`);

  addObject(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents ${streamObjId} 0 R /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> >>`);

  // Object 4: Font (Courier)
  addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Courier /Encoding /WinAnsiEncoding >>');

  // Object 5: Font (Courier-Bold)
  addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Courier-Bold /Encoding /WinAnsiEncoding >>');

  // Build PDF
  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];

  for (let i = 0; i < objects.length; i++) {
    offsets.push(pdf.length);
    pdf += `${objects[i]}\n`;
  }

  // Cross-reference table
  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objectCount + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (const offset of offsets) {
    pdf += `${offset.toString().padStart(10, '0')} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objectCount + 1} /Root ${catalogObj} 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'binary');
}

// ---- DOCX Generation ----
async function generateDocx(title: string, description: string, category: string, role: string) {
  try {
    const children: Paragraph[] = [];

    // Title
    children.push(new Paragraph({
      children: [new TextRun({ text: title, bold: true, size: 36 })],
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
    }));

    // Category & Role
    children.push(new Paragraph({
      children: [new TextRun({ text: `${category}  •  ${role}`, size: 18, color: '666666' })],
      alignment: AlignmentType.CENTER,
    }));

    children.push(new Paragraph({ text: '' }));

    // Description
    if (description) {
      children.push(new Paragraph({
        children: [new TextRun({ text: description, size: 22 })],
      }));
      children.push(new Paragraph({ text: '' }));
    }

    // Category-specific content
    const contentLines = getCategoryContent(category, role);
    for (const line of contentLines) {
      if (line.startsWith('## ')) {
        children.push(new Paragraph({
          children: [new TextRun({ text: line.replace('## ', ''), bold: true, size: 26 })],
          heading: HeadingLevel.HEADING_2,
        }));
      } else if (line.startsWith('# ')) {
        children.push(new Paragraph({
          children: [new TextRun({ text: line.replace('# ', ''), bold: true, size: 28 })],
          heading: HeadingLevel.HEADING_1,
        }));
      } else if (line.startsWith('- [ ] ')) {
        children.push(new Paragraph({
          children: [new TextRun({ text: `☐  ${line.replace('- [ ] ', '')}`, size: 22 })],
          indent: { left: 360 },
        }));
      } else if (line.startsWith('- ')) {
        children.push(new Paragraph({
          children: [new TextRun({ text: `•  ${line.replace('- ', '')}`, size: 22 })],
          indent: { left: 360 },
        }));
      } else if (line.trim() === '') {
        children.push(new Paragraph({ text: '' }));
      } else {
        children.push(new Paragraph({
          children: [new TextRun({ text: line, size: 22 })],
        }));
      }
    }

    // Footer
    children.push(new Paragraph({ text: '' }));
    children.push(new Paragraph({
      children: [new TextRun({ text: 'Generated by Amazon VA Interview Lab', size: 16, color: '999999', italics: true })],
      alignment: AlignmentType.CENTER,
    }));

    const doc = new Document({
      sections: [{ properties: {}, children }],
    });

    const buffer = await Packer.toBuffer(doc);
    const safeName = title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 50);

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${safeName}.docx"`,
      },
    });
  } catch (error) {
    console.error('DOCX generation error:', error);
    // Fallback to text
    const textContent = buildTextContent(title, description, category, role);
    return new NextResponse(textContent, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="${title.replace(/[^a-zA-Z0-9]/g, '_')}.txt"`,
      },
    });
  }
}

// ---- XLSX Generation ----
async function generateXlsx(title: string, description: string, category: string, role: string) {
  try {
    const ExcelJS = (await import('exceljs')).default;
    const workbook = new ExcelJS.Workbook();

    if (category === 'Calculators') {
      // Calculator spreadsheet with formulas
      const sheet = workbook.addWorksheet('Calculator');
      sheet.columns = [
        { header: 'Metric', key: 'metric', width: 25 },
        { header: 'Value', key: 'value', width: 20 },
        { header: 'Formula / Result', key: 'result', width: 30 },
      ];

      sheet.addRow({ metric: title, value: '', result: '' });
      sheet.addRow({ metric: '', value: '', result: '' });

      if (role.includes('PPC')) {
        sheet.addRow({ metric: 'ACoS Calculator', value: '', result: '' });
        sheet.addRow({ metric: 'Ad Spend ($)', value: 0, result: 'Enter your ad spend' });
        sheet.addRow({ metric: 'Ad Revenue ($)', value: 0, result: 'Enter your ad revenue' });
        sheet.addRow({ metric: 'ACoS (%)', value: '', result: '=IF(B5>0,B4/B5*100,"N/A")' });
        sheet.addRow({ metric: '', value: '', result: '' });
        sheet.addRow({ metric: 'ROAS Calculator', value: '', result: '' });
        sheet.addRow({ metric: 'Ad Revenue ($)', value: 0, result: 'Enter your ad revenue' });
        sheet.addRow({ metric: 'Ad Spend ($)', value: 0, result: 'Enter your ad spend' });
        sheet.addRow({ metric: 'ROAS (x)', value: '', result: '=IF(B10>0,B9/B10,"N/A")' });
        sheet.addRow({ metric: '', value: '', result: '' });
        sheet.addRow({ metric: 'Break-even ACoS', value: '', result: '' });
        sheet.addRow({ metric: 'Product Price ($)', value: 0, result: 'Enter product price' });
        sheet.addRow({ metric: 'Product Cost ($)', value: 0, result: 'Enter product cost' });
        sheet.addRow({ metric: 'FBA Fees ($)', value: 0, result: 'Enter FBA fees' });
        sheet.addRow({ metric: 'Break-even ACoS (%)', value: '', result: '=IF(B15>0,(B15-B16-B17)/B15*100,"N/A")' });
      } else {
        sheet.addRow({ metric: 'Profit Margin Calculator', value: '', result: '' });
        sheet.addRow({ metric: 'Revenue ($)', value: 0, result: 'Enter revenue' });
        sheet.addRow({ metric: 'COGS ($)', value: 0, result: 'Enter cost of goods sold' });
        sheet.addRow({ metric: 'FBA Fees ($)', value: 0, result: 'Enter FBA fees' });
        sheet.addRow({ metric: 'Ad Spend ($)', value: 0, result: 'Enter advertising spend' });
        sheet.addRow({ metric: 'Profit Margin (%)', value: '', result: '=IF(B5>0,(B5-B6-B7-B8)/B5*100,"N/A")' });
      }

      // Style the header row
      sheet.getRow(1).font = { bold: true };
      sheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2563EB' } };
      sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };

      // Style calculator section headers
      const sectionRows = [3, 8, 12];
      for (const rowNum of sectionRows) {
        const row = sheet.getRow(rowNum);
        if (row.getCell(1).value) {
          row.font = { bold: true, size: 12 };
        }
      }

    } else {
      // General tracking spreadsheet
      const sheet = workbook.addWorksheet(title.replace(/[^a-zA-Z0-9]/g, ' ').substring(0, 31));
      sheet.columns = [
        { header: 'Item', key: 'item', width: 30 },
        { header: 'Status', key: 'status', width: 15 },
        { header: 'Notes', key: 'notes', width: 40 },
        { header: 'Due Date', key: 'dueDate', width: 15 },
      ];

      // Style header
      sheet.getRow(1).font = { bold: true };
      sheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2563EB' } };
      sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };

      // Add checklist items
      const items = getChecklistItems(category, role);
      for (const item of items) {
        sheet.addRow({ item, status: 'Pending', notes: '', dueDate: '' });
      }
    }

    const buffer = await workbook.xlsx.writeBuffer();
    const safeName = title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 50);

    return new NextResponse(new Uint8Array(Buffer.from(buffer)), {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="${safeName}.xlsx"`,
      },
    });
  } catch (error) {
    console.error('XLSX generation error:', error);
    // Fallback to text
    const textContent = buildTextContent(title, description, category, role);
    return new NextResponse(textContent, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="${title.replace(/[^a-zA-Z0-9]/g, '_')}.txt"`,
      },
    });
  }
}

function getChecklistItems(category: string, role: string): string[] {
  if (category === 'Checklists') {
    if (role.includes('PPC')) {
      return [
        'Review search term reports',
        'Add high-converting search terms as exact keywords',
        'Negate irrelevant search terms',
        'Adjust bids based on ACoS targets',
        'Check budget utilization',
        'Review placement performance',
        'Pause underperforming campaigns',
        'Update negative keyword lists',
      ];
    }
    if (role.includes('Account')) {
      return [
        'Check account health dashboard',
        'Review FBA inventory alerts',
        'Process reimbursement cases',
        'Update listing statuses',
        'Review seller feedback',
        'Check restock recommendations',
      ];
    }
    return [
      'Log in to Seller Central',
      'Check notifications and alerts',
      'Review advertising performance',
      'Check inventory levels',
      'Respond to buyer messages',
      'Prepare client update',
    ];
  }
  // For other categories, provide general tracking items
  return [
    'Item 1',
    'Item 2',
    'Item 3',
    'Item 4',
    'Item 5',
  ];
}

function getCategoryContent(category: string, role: string): string[] {
  const lines: string[] = [];

  switch (category) {
    case 'Cheat Sheets':
      lines.push('## Quick Reference');
      lines.push('');
      if (role.includes('PPC')) {
        lines.push('## Key Formulas');
        lines.push('ACoS = Ad Spend / Ad Revenue × 100');
        lines.push('ROAS = Ad Revenue / Ad Spend');
        lines.push('CTR = Clicks / Impressions × 100');
        lines.push('CPC = Total Spend / Total Clicks');
        lines.push('CVR = Orders / Clicks × 100');
        lines.push('');
        lines.push('## Campaign Types');
        lines.push('- Sponsored Products (keyword & product targeting)');
        lines.push('- Sponsored Brands (headline search ads)');
        lines.push('- Sponsored Display (audience & contextual)');
        lines.push('');
        lines.push('## Match Types');
        lines.push('- Exact Match: Precise keyword targeting');
        lines.push('- Phrase Match: Keyword + close variations');
        lines.push('- Broad Match: Wide reach, many variations');
      } else if (role.includes('Account')) {
        lines.push('## Account Health Metrics');
        lines.push('- Order Defect Rate: Keep below 1%');
        lines.push('- Late Shipment Rate: Keep below 4%');
        lines.push('- Pre-fulfillment Cancel Rate: Keep below 2.5%');
        lines.push('');
        lines.push('## Fee Structure');
        lines.push('- Referral Fee: 8-15% depending on category');
        lines.push('- FBA Fee: Based on size & weight tiers');
        lines.push('- Monthly Storage: $0.69-$2.40 per cubic foot');
      } else if (role.includes('Listing')) {
        lines.push('## Listing Optimization Checklist');
        lines.push('- Title: Brand + Key Feature + Size/Color + Keyword');
        lines.push('- Bullets: 5 bullets, feature → benefit format');
        lines.push('- Backend Keywords: 250 bytes max, no repeats');
        lines.push('- Images: 1000x1000px minimum, white background main image');
        lines.push('- A+ Content: Enhanced brand content for brand-registered sellers');
      } else if (role.includes('Reporting')) {
        lines.push('## Key Reports');
        lines.push('- Search Term Report: Find converting keywords');
        lines.push('- Placement Report: Top of Search vs Rest of Search');
        lines.push('- Campaign Report: Overall performance snapshot');
        lines.push('- Advertised Product Report: ASIN-level data');
        lines.push('');
        lines.push('## Date Ranges');
        lines.push('- 7-day: Quick trend check');
        lines.push('- 14-day: Optimization cycle');
        lines.push('- 30-day: Strategic review');
      } else {
        lines.push('## Seller Central Navigation');
        lines.push('- Catalog → Advertising → Reports → Settings');
        lines.push('');
        lines.push('## Common Acronyms');
        lines.push('- ASIN: Amazon Standard Identification Number');
        lines.push('- SKU: Stock Keeping Unit');
        lines.push('- FBA: Fulfillment by Amazon');
        lines.push('- ACoS: Advertising Cost of Sales');
        lines.push('- ROAS: Return on Ad Spend');
      }
      break;

    case 'Checklists':
      lines.push('## Daily / Weekly Tasks');
      lines.push('');
      if (role.includes('PPC')) {
        lines.push('- [ ] Review search term reports');
        lines.push('- [ ] Add high-converting search terms as exact keywords');
        lines.push('- [ ] Negate irrelevant search terms');
        lines.push('- [ ] Adjust bids based on ACoS targets');
        lines.push('- [ ] Check budget utilization');
        lines.push('- [ ] Review placement performance');
        lines.push('- [ ] Pause underperforming campaigns/ad groups');
        lines.push('- [ ] Update negative keyword lists');
      } else if (role.includes('Account')) {
        lines.push('- [ ] Check account health dashboard');
        lines.push('- [ ] Review FBA inventory alerts');
        lines.push('- [ ] Process reimbursement cases');
        lines.push('- [ ] Update listing statuses');
        lines.push('- [ ] Review seller feedback');
        lines.push('- [ ] Check restock recommendations');
        lines.push('- [ ] Monitor stranded inventory');
      } else if (role.includes('Listing')) {
        lines.push('- [ ] Review listing quality score');
        lines.push('- [ ] Optimize titles with keywords');
        lines.push('- [ ] Update bullet points');
        lines.push('- [ ] Add A+ content');
        lines.push('- [ ] Upload high-quality images');
        lines.push('- [ ] Review backend search terms');
        lines.push('- [ ] Check for suppressed listings');
      } else {
        lines.push('- [ ] Log in to Seller Central');
        lines.push('- [ ] Check notifications and alerts');
        lines.push('- [ ] Review advertising performance');
        lines.push('- [ ] Check inventory levels');
        lines.push('- [ ] Respond to buyer messages');
        lines.push('- [ ] Review listing quality');
        lines.push('- [ ] Prepare client update');
      }
      break;

    case 'Calculators':
      lines.push('## ACoS Calculator');
      lines.push('Ad Spend: [enter amount]');
      lines.push('Ad Revenue: [enter amount]');
      lines.push('ACoS = Ad Spend / Ad Revenue × 100 = [result]%');
      lines.push('');
      lines.push('## ROAS Calculator');
      lines.push('Ad Revenue: [enter amount]');
      lines.push('Ad Spend: [enter amount]');
      lines.push('ROAS = Ad Revenue / Ad Spend = [result]x');
      lines.push('');
      lines.push('## Break-even ACoS');
      lines.push('Product Price: [enter amount]');
      lines.push('Product Cost: [enter amount]');
      lines.push('FBA Fees: [enter amount]');
      lines.push('Break-even ACoS = (Price - Cost - Fees) / Price × 100 = [result]%');
      lines.push('');
      lines.push('Note: Download the XLSX version for an interactive calculator with formulas.');
      break;

    case 'Resume Templates':
      lines.push('[YOUR FULL NAME]');
      lines.push('[City, Country] | [Email] | [Phone] | [LinkedIn URL]');
      lines.push('');
      lines.push('## Professional Summary');
      lines.push(`Results-driven ${role || 'Amazon VA'} with [X] years of experience in Amazon marketplace operations. Skilled in [key skills]. Proven track record of [achievements with metrics].`);
      lines.push('');
      lines.push('## Core Skills');
      lines.push('- Amazon Seller Central & Advertising Console');
      lines.push('- Keyword Research & Bid Optimization');
      lines.push('- Data Analysis & Reporting');
      lines.push('- Client Communication & Account Management');
      lines.push('');
      lines.push('## Professional Experience');
      lines.push('[Job Title] | [Company] | [Date Range]');
      lines.push('- Managed [X] campaigns with $[Y] monthly spend, achieving [Z]% ACoS');
      lines.push('- [Action verb + specific task + quantified result]');
      lines.push('- [Another achievement with metrics]');
      lines.push('');
      lines.push('## Tools & Platforms');
      lines.push('Amazon Seller Central, Amazon Ads Console, Helium 10, Google Sheets, Excel');
      lines.push('');
      lines.push('## Education');
      lines.push('[Degree] | [University] | [Year]');
      break;

    case 'Cover Letters':
      lines.push('[Date]');
      lines.push('');
      lines.push('[Hiring Manager Name]');
      lines.push('[Company Name]');
      lines.push('');
      lines.push('Dear [Hiring Manager],');
      lines.push('');
      lines.push(`I am writing to express my interest in the ${role || 'Amazon Virtual Assistant'} position at [Company Name]. With my experience in Amazon marketplace operations and commitment to delivering measurable results, I am confident I can make an immediate impact on your team.`);
      lines.push('');
      lines.push(`In my previous role, I [specific achievement with metrics relevant to ${role}]. I am particularly skilled in [2-3 specific skills relevant to the role].`);
      lines.push('');
      lines.push('I would welcome the opportunity to discuss how my skills align with your needs. Thank you for your consideration.');
      lines.push('');
      lines.push('Best regards,');
      lines.push('[Your Name]');
      break;

    case 'Plans & Reports':
      lines.push('## Weekly Report Template');
      lines.push('');
      lines.push('Period: [Start Date] - [End Date]');
      lines.push('Client: [Client Name]');
      lines.push(`Role Focus: ${role}`);
      lines.push('');
      lines.push('## Key Metrics');
      lines.push('- Total Spend: $[amount]');
      lines.push('- Total Revenue: $[amount]');
      lines.push('- ACoS: [percentage]%');
      lines.push('- ROAS: [value]x');
      lines.push('- Impressions: [number]');
      lines.push('- Clicks: [number]');
      lines.push('- Orders: [number]');
      lines.push('');
      lines.push('## Highlights');
      lines.push('- [Key achievement or improvement]');
      lines.push('- [Notable metric change]');
      lines.push('');
      lines.push('## Action Items');
      lines.push('- [Planned optimization]');
      lines.push('- [Budget adjustment needed]');
      break;

    default:
      lines.push('## Notes');
      lines.push('');
      lines.push('[Your notes here]');
  }

  return lines;
}
